export const searchBarOptions: Map<string, string> = new Map();

searchBarOptions.set("Button", "/Button");
searchBarOptions.set("Search Bar", "/SearchBar");
searchBarOptions.set("Title & Subtitle", "/Title&Subtitle");
searchBarOptions.set("Plane Trail", "/PlaneTrail");
searchBarOptions.set("File Downloader", "/FileDownloader");
searchBarOptions.set("Footer", "/Footer");
searchBarOptions.set("App Logo", "/WavelengthAppLogo");
searchBarOptions.set("Brown Box", "/BrownBox");
searchBarOptions.set("Placeholder", "/Placeholder");
searchBarOptions.set("Autocomplete", "/Autocomplete");
searchBarOptions.set("Many Planes", "/ManyPlanes");
searchBarOptions.set("Confirmation Modal", "/ConfirmationModal");
searchBarOptions.set("Banner", "/Banner");
searchBarOptions.set("Pop Up Menu", "/PopUpMenu");
searchBarOptions.set("Snack Bar", "/SnackBar");
searchBarOptions.set("Page Not Available", "/PageNotAvailable");
searchBarOptions.set("Standard Snackbar", "/StandardSnackbar");
searchBarOptions.set("Side Bar", "/SideBar");
searchBarOptions.set("Slider", "/Slider");
searchBarOptions.set("Styled Button", "/StyledButton");
searchBarOptions.set("Text Field", "/TextField");
searchBarOptions.set("Spinning Logo", "/SpinningLogo");
searchBarOptions.set("Dropdown Menu", "/DropDownMenu");
searchBarOptions.set("Carousel", "/Carousel");
searchBarOptions.set("Drag and Drop", "/DragAndDrop");
searchBarOptions.set("Progress Bar", "/ProgressBar");
searchBarOptions.set("Comment", "/CommentDisplay");
